eureka:
    client:
        fetch-registry: false
        register-with-eureka: true
        service-url:
            defaultZone: http://peer2:1112/eureka/
    instance:
        hostname: peer1
server:
    port: 1111
spring:
    application:
        name: eureka-server
