eureka:
    client:
        fetch-registry: false
        register-with-eureka: true
        service-url:
            defaultZone: http://peer1:1111/eureka/
    instance:
        hostname: peer2
server:
    port: 1112
spring:
    application:
        name: eureka-server
